parameters:
    vendor: !php/const NP_STANDARDS_INTERNAL_VENDOR

phpcpd:
    min_lines:
        default: 5
        description: The minimum number of lines which need to be duplicated to count as copy/paste
    min_tokens:
        default: 70
        description: The minimum number of duplicated tokens within a line to count as copy/paste
phpcs:
    standards:
        default: '%vendor%../sniffs/NatePage'
        description: The standards to compare code against, will be ignored if phpcs.xml exists
    show_sniff_name:
        default: true
        description: Whether to show the code sniffs name on report output
phpmd:
    rule_sets:
        default: cleancode,codesize,controversial,design,naming,unusedcode
        description: The rulesets to use to determine issues, will be ignored if phpmd.xml exists
phpstan:
    reporting_level:
        default: 7
        description: The reporting level, 1 = loose, 7 = strict
phpunit:
    config_file:
        default: phpunit.xml
        description: Config file to use to run PHPUnit
    coverage_minimum_level:
        default: 90
        description: The minimum percentage of coverage to have, will be ignored if coverage check is disabled
    enable_code_coverage:
        default: true
        description: Whether or not to enable code coverage checks
    junit_log_path:
        description: The path to output junit parseable log file, can be relative, will be ignored if left blank
    test_directory:
        default: tests
        description: The directory containing tests, will be ignored it phpunit.xml exists in working directory
